#- name: Install gobrew
#shell: curl -L https://raw.github.com/grobins2/gobrew/master/tools/install.sh | sh
#  args:
#    creates: ~/.gobrew
#

- name: Install gobrew
  git: repo=https://github.com/anarcher/gobrew.git dest=~/.gobrew/ 

- name: Setup gobrew in bashprofile 1/2
  lineinfile: dest=~/.bash_profile line='export PATH="$HOME/.gobrew/bin:$PATH"'

- name: Setup gobrew in bashprofile 2/2
  lineinfile: dest=~/.bash_profile line="eval \"$(gobrew init -)\""

- name: Install golang
  shell: ~/.gobrew/bin/gobrew install {{ go_version }} 
  args:
      creates: ~/.gobrew/versions/{{ go_version }}

- name: Use golang 
  shell: ~/.gobrew/bin/gobrew use {{ go_version }}

- name: Mkdir {{ go_path }}
  file: dest=~/go state=directory

- name: Setup GOPATH
  lineinfile: dest=~/.bash_profile line='export GOPATH={{ go_path }}'

- name: Append GOPATH to PATH
  lineinfile: dest=~/.bash_profile line='export PATH=$PATH:$GOPATH'

- name: Install goenv (0.4.2)
  copy: src="goenv_linux" dest="~/bin/goenv" mode=0774
  when: "ansible_os_family == 'Debian'"

- name: Install godep (2015.02.15 built)
  copy: src="godep_linux" dest="~/bin/godep" mode=0774
  when: "ansible_os_family == 'Debian'"

- name: Install goenv (0.4.2)
  copy: src="goenv_osx" dest="~/bin/goenv" mode=0774
  when: "ansible_os_family == 'MacOSX'"

- name: Install godep (2015.02.15 built)
  copy: src="godep_osx" dest="~/bin/godep" mode=0774
  when: "ansible_os_family == 'MacOSX'"

- include: gxui.yml

