---

#- name: Install zsh 
#  apt: pkg=zsh state=latest
#  when: "ansible_os_family == 'Debian'"
#  sudo: yes

- name: Install command packages via apt
  apt: pkg={{ item }} state=latest
  with_items: debs
  sudo: yes

