---

- name: Install zsh 
  apt: pkg=zsh state=latest
  when: "ansible_os_family == 'Debian'"
  sudo: yes

- name: Install zsh (brew)
  homebrew: pkg=zsh state=latest
  when: "ansible_os_family == 'MacOSX'"

#- name: Install oh-my-zsh 
#  sudo: false
#  shell: curl -L http://install.ohmyz.sh | sh
#  args:
#      creates: ~/.oh-my-zsh

#- name: Copy zshrc 
#  sudo: false
#  copy: src=zshrc dest=~/.zshrc 

- name: Install fzf (https://github.com/junegunn/fzf)
  sudo: false
  shell: git clone https://github.com/junegunn/fzf.git ~/.fzf ; ~/.fzf/install 
  args:
      creates: ~/.fzf/install

#- name: Install autojump (https://github.com/joelthelion/autojump)
#  apt: pkg=autojump
#  when: "ansible_os_family == 'Debian'"
#  sudo: yes
# bash with autojump has some bug. http://unix.stackexchange.com/questions/129348/autojump-auto-complete-feature-does-not-work

- name: Git clone autojump
  git: repo=git://github.com/joelthelion/autojump.git dest=/tmp/autojump
  
- name: Install autojump
  shell: cd /tmp/autojump && ./install.py

- name: Configure autojump in bash 
  lineinfile: dest=~/.bash_profile line="[[ -s /home/{{ ansible_user_id }}/.autojump/etc/profile.d/autojump.sh ]] && source /home/{{ ansible_user_id }}/.autojump/etc/profile.d/autojump.sh"
  when: "ansible_os_family == 'Debian'"

- name: Install autojump via brew (https://github.com/joelthelion/autojump)
  command: brew install autojump
  when: "ansible_os_family == 'MacOSX'"

- name: Configure autojump in bash
  lineinfile: dest=~/.bash_profile line="source /usr/share/autojump/autojump.bash"
  when: "ansible_os_family == 'MacOSX'"

- name: Install command packages via apt
  apt: pkg={{ item }} state=latest
  with_items: debs
  when: "ansible_os_family == 'Debian'"
  sudo: yes

- name: Install command packages via brew
  homebrew: pkg={{ item }} state=latest
  with_items: brews
  when: "ansible_os_family == 'MacOSX'"

- name: Copy git.bash
  copy: src=git.bash dest="~/.git.bash"

- name: Source git.bash
  lineinfile: dest=~/.bash_profile line="source ~/.git.bash"
