---

- name: Install zsh 
  apt: pkg=zsh state=latest
  when: "ansible_os_family == 'Debian'"
  sudo: yes

- name: Install zsh (brew)
  homebrew: pkg=zsh state=latest
  when: "ansible_os_family == 'MacOSX'"

#- name: Install oh-my-zsh 
#  sudo: false
#  shell: curl -L http://install.ohmyz.sh | sh
#  args:
#      creates: ~/.oh-my-zsh

#- name: Copy zshrc 
#  sudo: false
#  copy: src=zshrc dest=~/.zshrc 

- name: Install fzf (https://github.com/junegunn/fzf)
  sudo: false
  shell: git clone https://github.com/junegunn/fzf.git ~/.fzf ; ~/.fzf/install 
  args:
      creates: ~/.fzf/install

- name: Install autojump (https://github.com/joelthelion/autojump)
  apt: pkg=autojump
  when: "ansible_os_family == 'Debian'"
  sudo: yes


- name: Install autojump via brew (https://github.com/joelthelion/autojump)
  command: brew install autojump
  when: "ansible_os_family == 'MacOSX'"

- name: Configure autojump in bash
  lineinfile: dest=~/.bash_profile line="source /usr/share/autojump/autojump.bash"

- name: Install command packages via apt
  apt: pkg={{ item }} state=latest
  with_items: debs
  when: "ansible_os_family == 'Debian'"
  sudo: yes

- name: Install command packages via brew
  homebrew: pkg={{ item }} state=latest
  with_items: brews
  when: "ansible_os_family == 'MacOSX'"

- name: Copy git.bash
  copy: src=git.bash dest="~/.git.bash"

- name: Source git.bash
  lineinfile: dest=~/.bash_profile line="source ~/.git.bash"
