---

#- name: Install zsh (brew)
#  homebrew: pkg=zsh state=latest
#  when: "ansible_os_family == 'MacOSX'"

#- name: Install oh-my-zsh 
#  sudo: false
#  shell: curl -L http://install.ohmyz.sh | sh
#  args:
#      creates: ~/.oh-my-zsh

#- name: Copy zshrc 
#  sudo: false
#  copy: src=zshrc dest=~/.zshrc 

- name: Install command packages via brew
  homebrew: pkg={{ item }} state=latest
  with_items: brews

