---
- hosts: 127.0.0.1
  connection: local
  sudo: no
  roles:
      - base
      - shell
      - doc
      - editor
      - golang
      - python
      - javascript
      - docker
      - desktop
      - notebook
      - webbrowser
      - gnome
      - vm
