- name: Install synergy
  apt: pkg=synergy
  sudo: yes

- name: Copy synergy.conf (server)
  copy: src="synergy.conf" dest="/etc/synergy.conf"
  sudo: yes

- name: Install dconf-editor
  apt: pkg=dconf-editor
  sudo: yes


