" set 
set guifont=Mensch\ Regular:h24
set nocompatible
set autoindent
set smarttab
set expandtab
set tabstop=4
set shiftwidth=4
set visualbell
set fileencodings=ucs-bom,utf-8,euc-kr
set mouse=

syntax on
"colo pablo
colo ron

" pathogen 
execute pathogen#infect()
syntax on
filetype plugin indent on


" vim-golang
autocmd FileType go autocmd BufWritePre <buffer> Fmt

