- name: Add docker apt repository key
  sudo: yes
  apt_key: url=https://get.docker.io/gpg state=present validate_certs=no

- name: Add docker apt repository
  sudo: yes
  apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present

- name: Install latest docker via apt
  sudo: yes
  apt: pkg=lxc-docker state=latest 

- name: Add user to Docker group
  sudo: yes
  user: name={{ ansible_user_id }} groups=docker append=yes
#  group: name=docker state=present

- name: Start docker on boot
  sudo: yes
  service: name=docker state=started enabled=yes

- name: Docker aliases
  sudo: yes
  copy: src=docker_aliases.sh dest=/etc/profile.d/docker_aliases.sh
        mode=0644 owner=root group=root
