- name: Add docker apt repository key
  sudo: yes
  apt_key: url=https://get.docker.io/gpg state=present validate_certs=no

- name: Add docker apt repository
  sudo: yes
  apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present

- name: Install latest docker via apt
  sudo: yes
  apt: pkg=lxc-docker state=latest 
